// +build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Alarm) DeepCopyInto(out *Alarm) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Alarm.
func (in *Alarm) DeepCopy() *Alarm {
	if in == nil {
		return nil
	}
	out := new(Alarm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlarmConfiguration) DeepCopyInto(out *AlarmConfiguration) {
	*out = *in
	if in.Alarms != nil {
		in, out := &in.Alarms, &out.Alarms
		*out = make([]*Alarm, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Alarm)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.IgnorePollAlarmFailure != nil {
		in, out := &in.IgnorePollAlarmFailure, &out.IgnorePollAlarmFailure
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlarmConfiguration.
func (in *AlarmConfiguration) DeepCopy() *AlarmConfiguration {
	if in == nil {
		return nil
	}
	out := new(AlarmConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppSpecContent) DeepCopyInto(out *AppSpecContent) {
	*out = *in
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(string)
		**out = **in
	}
	if in.SHA256 != nil {
		in, out := &in.SHA256, &out.SHA256
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSpecContent.
func (in *AppSpecContent) DeepCopy() *AppSpecContent {
	if in == nil {
		return nil
	}
	out := new(AppSpecContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Application) DeepCopyInto(out *Application) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Application.
func (in *Application) DeepCopy() *Application {
	if in == nil {
		return nil
	}
	out := new(Application)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Application) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationInfo) DeepCopyInto(out *ApplicationInfo) {
	*out = *in
	if in.ApplicationID != nil {
		in, out := &in.ApplicationID, &out.ApplicationID
		*out = new(string)
		**out = **in
	}
	if in.ApplicationName != nil {
		in, out := &in.ApplicationName, &out.ApplicationName
		*out = new(string)
		**out = **in
	}
	if in.ComputePlatform != nil {
		in, out := &in.ComputePlatform, &out.ComputePlatform
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = (*in).DeepCopy()
	}
	if in.GitHubAccountName != nil {
		in, out := &in.GitHubAccountName, &out.GitHubAccountName
		*out = new(string)
		**out = **in
	}
	if in.LinkedToGitHub != nil {
		in, out := &in.LinkedToGitHub, &out.LinkedToGitHub
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationInfo.
func (in *ApplicationInfo) DeepCopy() *ApplicationInfo {
	if in == nil {
		return nil
	}
	out := new(ApplicationInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationList) DeepCopyInto(out *ApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Application, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationList.
func (in *ApplicationList) DeepCopy() *ApplicationList {
	if in == nil {
		return nil
	}
	out := new(ApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSpec) DeepCopyInto(out *ApplicationSpec) {
	*out = *in
	if in.ApplicationName != nil {
		in, out := &in.ApplicationName, &out.ApplicationName
		*out = new(string)
		**out = **in
	}
	if in.ComputePlatform != nil {
		in, out := &in.ComputePlatform, &out.ComputePlatform
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSpec.
func (in *ApplicationSpec) DeepCopy() *ApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationStatus) DeepCopyInto(out *ApplicationStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(v1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*v1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ApplicationID != nil {
		in, out := &in.ApplicationID, &out.ApplicationID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationStatus.
func (in *ApplicationStatus) DeepCopy() *ApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoRollbackConfiguration) DeepCopyInto(out *AutoRollbackConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoRollbackConfiguration.
func (in *AutoRollbackConfiguration) DeepCopy() *AutoRollbackConfiguration {
	if in == nil {
		return nil
	}
	out := new(AutoRollbackConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalingGroup) DeepCopyInto(out *AutoScalingGroup) {
	*out = *in
	if in.Hook != nil {
		in, out := &in.Hook, &out.Hook
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalingGroup.
func (in *AutoScalingGroup) DeepCopy() *AutoScalingGroup {
	if in == nil {
		return nil
	}
	out := new(AutoScalingGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueGreenDeploymentConfiguration) DeepCopyInto(out *BlueGreenDeploymentConfiguration) {
	*out = *in
	if in.DeploymentReadyOption != nil {
		in, out := &in.DeploymentReadyOption, &out.DeploymentReadyOption
		*out = new(DeploymentReadyOption)
		(*in).DeepCopyInto(*out)
	}
	if in.GreenFleetProvisioningOption != nil {
		in, out := &in.GreenFleetProvisioningOption, &out.GreenFleetProvisioningOption
		*out = new(GreenFleetProvisioningOption)
		(*in).DeepCopyInto(*out)
	}
	if in.TerminateBlueInstancesOnDeploymentSuccess != nil {
		in, out := &in.TerminateBlueInstancesOnDeploymentSuccess, &out.TerminateBlueInstancesOnDeploymentSuccess
		*out = new(BlueInstanceTerminationOption)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueGreenDeploymentConfiguration.
func (in *BlueGreenDeploymentConfiguration) DeepCopy() *BlueGreenDeploymentConfiguration {
	if in == nil {
		return nil
	}
	out := new(BlueGreenDeploymentConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueInstanceTerminationOption) DeepCopyInto(out *BlueInstanceTerminationOption) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.TerminationWaitTimeInMinutes != nil {
		in, out := &in.TerminationWaitTimeInMinutes, &out.TerminationWaitTimeInMinutes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueInstanceTerminationOption.
func (in *BlueInstanceTerminationOption) DeepCopy() *BlueInstanceTerminationOption {
	if in == nil {
		return nil
	}
	out := new(BlueInstanceTerminationOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudFormationTarget) DeepCopyInto(out *CloudFormationTarget) {
	*out = *in
	if in.DeploymentID != nil {
		in, out := &in.DeploymentID, &out.DeploymentID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudFormationTarget.
func (in *CloudFormationTarget) DeepCopy() *CloudFormationTarget {
	if in == nil {
		return nil
	}
	out := new(CloudFormationTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Deployment) DeepCopyInto(out *Deployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Deployment.
func (in *Deployment) DeepCopy() *Deployment {
	if in == nil {
		return nil
	}
	out := new(Deployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Deployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfig) DeepCopyInto(out *DeploymentConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfig.
func (in *DeploymentConfig) DeepCopy() *DeploymentConfig {
	if in == nil {
		return nil
	}
	out := new(DeploymentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfigInfo) DeepCopyInto(out *DeploymentConfigInfo) {
	*out = *in
	if in.ComputePlatform != nil {
		in, out := &in.ComputePlatform, &out.ComputePlatform
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = (*in).DeepCopy()
	}
	if in.DeploymentConfigID != nil {
		in, out := &in.DeploymentConfigID, &out.DeploymentConfigID
		*out = new(string)
		**out = **in
	}
	if in.DeploymentConfigName != nil {
		in, out := &in.DeploymentConfigName, &out.DeploymentConfigName
		*out = new(string)
		**out = **in
	}
	if in.MinimumHealthyHosts != nil {
		in, out := &in.MinimumHealthyHosts, &out.MinimumHealthyHosts
		*out = new(MinimumHealthyHosts)
		(*in).DeepCopyInto(*out)
	}
	if in.TrafficRoutingConfig != nil {
		in, out := &in.TrafficRoutingConfig, &out.TrafficRoutingConfig
		*out = new(TrafficRoutingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfigInfo.
func (in *DeploymentConfigInfo) DeepCopy() *DeploymentConfigInfo {
	if in == nil {
		return nil
	}
	out := new(DeploymentConfigInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfigList) DeepCopyInto(out *DeploymentConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeploymentConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfigList.
func (in *DeploymentConfigList) DeepCopy() *DeploymentConfigList {
	if in == nil {
		return nil
	}
	out := new(DeploymentConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfigSpec) DeepCopyInto(out *DeploymentConfigSpec) {
	*out = *in
	if in.ComputePlatform != nil {
		in, out := &in.ComputePlatform, &out.ComputePlatform
		*out = new(string)
		**out = **in
	}
	if in.DeploymentConfigName != nil {
		in, out := &in.DeploymentConfigName, &out.DeploymentConfigName
		*out = new(string)
		**out = **in
	}
	if in.MinimumHealthyHosts != nil {
		in, out := &in.MinimumHealthyHosts, &out.MinimumHealthyHosts
		*out = new(MinimumHealthyHosts)
		(*in).DeepCopyInto(*out)
	}
	if in.TrafficRoutingConfig != nil {
		in, out := &in.TrafficRoutingConfig, &out.TrafficRoutingConfig
		*out = new(TrafficRoutingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfigSpec.
func (in *DeploymentConfigSpec) DeepCopy() *DeploymentConfigSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfigStatus) DeepCopyInto(out *DeploymentConfigStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(v1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*v1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.DeploymentConfigID != nil {
		in, out := &in.DeploymentConfigID, &out.DeploymentConfigID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfigStatus.
func (in *DeploymentConfigStatus) DeepCopy() *DeploymentConfigStatus {
	if in == nil {
		return nil
	}
	out := new(DeploymentConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentGroup) DeepCopyInto(out *DeploymentGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentGroup.
func (in *DeploymentGroup) DeepCopy() *DeploymentGroup {
	if in == nil {
		return nil
	}
	out := new(DeploymentGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentGroupInfo) DeepCopyInto(out *DeploymentGroupInfo) {
	*out = *in
	if in.AlarmConfiguration != nil {
		in, out := &in.AlarmConfiguration, &out.AlarmConfiguration
		*out = new(AlarmConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplicationName != nil {
		in, out := &in.ApplicationName, &out.ApplicationName
		*out = new(string)
		**out = **in
	}
	if in.AutoRollbackConfiguration != nil {
		in, out := &in.AutoRollbackConfiguration, &out.AutoRollbackConfiguration
		*out = new(AutoRollbackConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoScalingGroups != nil {
		in, out := &in.AutoScalingGroups, &out.AutoScalingGroups
		*out = make([]*AutoScalingGroup, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(AutoScalingGroup)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.BlueGreenDeploymentConfiguration != nil {
		in, out := &in.BlueGreenDeploymentConfiguration, &out.BlueGreenDeploymentConfiguration
		*out = new(BlueGreenDeploymentConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ComputePlatform != nil {
		in, out := &in.ComputePlatform, &out.ComputePlatform
		*out = new(string)
		**out = **in
	}
	if in.DeploymentConfigName != nil {
		in, out := &in.DeploymentConfigName, &out.DeploymentConfigName
		*out = new(string)
		**out = **in
	}
	if in.DeploymentGroupID != nil {
		in, out := &in.DeploymentGroupID, &out.DeploymentGroupID
		*out = new(string)
		**out = **in
	}
	if in.DeploymentGroupName != nil {
		in, out := &in.DeploymentGroupName, &out.DeploymentGroupName
		*out = new(string)
		**out = **in
	}
	if in.DeploymentStyle != nil {
		in, out := &in.DeploymentStyle, &out.DeploymentStyle
		*out = new(DeploymentStyle)
		(*in).DeepCopyInto(*out)
	}
	if in.EC2TagFilters != nil {
		in, out := &in.EC2TagFilters, &out.EC2TagFilters
		*out = make([]*EC2TagFilter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(EC2TagFilter)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.EC2TagSet != nil {
		in, out := &in.EC2TagSet, &out.EC2TagSet
		*out = new(EC2TagSet)
		(*in).DeepCopyInto(*out)
	}
	if in.EcsServices != nil {
		in, out := &in.EcsServices, &out.EcsServices
		*out = make([]*ECSService, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ECSService)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.LastAttemptedDeployment != nil {
		in, out := &in.LastAttemptedDeployment, &out.LastAttemptedDeployment
		*out = new(LastDeploymentInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.LastSuccessfulDeployment != nil {
		in, out := &in.LastSuccessfulDeployment, &out.LastSuccessfulDeployment
		*out = new(LastDeploymentInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancerInfo != nil {
		in, out := &in.LoadBalancerInfo, &out.LoadBalancerInfo
		*out = new(LoadBalancerInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.OnPremisesInstanceTagFilters != nil {
		in, out := &in.OnPremisesInstanceTagFilters, &out.OnPremisesInstanceTagFilters
		*out = make([]*TagFilter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TagFilter)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.OnPremisesTagSet != nil {
		in, out := &in.OnPremisesTagSet, &out.OnPremisesTagSet
		*out = new(OnPremisesTagSet)
		(*in).DeepCopyInto(*out)
	}
	if in.OutdatedInstancesStrategy != nil {
		in, out := &in.OutdatedInstancesStrategy, &out.OutdatedInstancesStrategy
		*out = new(string)
		**out = **in
	}
	if in.ServiceRoleARN != nil {
		in, out := &in.ServiceRoleARN, &out.ServiceRoleARN
		*out = new(string)
		**out = **in
	}
	if in.TargetRevision != nil {
		in, out := &in.TargetRevision, &out.TargetRevision
		*out = new(RevisionLocation)
		(*in).DeepCopyInto(*out)
	}
	if in.TriggerConfigurations != nil {
		in, out := &in.TriggerConfigurations, &out.TriggerConfigurations
		*out = make([]*TriggerConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TriggerConfig)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentGroupInfo.
func (in *DeploymentGroupInfo) DeepCopy() *DeploymentGroupInfo {
	if in == nil {
		return nil
	}
	out := new(DeploymentGroupInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentGroupList) DeepCopyInto(out *DeploymentGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeploymentGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentGroupList.
func (in *DeploymentGroupList) DeepCopy() *DeploymentGroupList {
	if in == nil {
		return nil
	}
	out := new(DeploymentGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentGroupSpec) DeepCopyInto(out *DeploymentGroupSpec) {
	*out = *in
	if in.AlarmConfiguration != nil {
		in, out := &in.AlarmConfiguration, &out.AlarmConfiguration
		*out = new(AlarmConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplicationName != nil {
		in, out := &in.ApplicationName, &out.ApplicationName
		*out = new(string)
		**out = **in
	}
	if in.AutoRollbackConfiguration != nil {
		in, out := &in.AutoRollbackConfiguration, &out.AutoRollbackConfiguration
		*out = new(AutoRollbackConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoScalingGroups != nil {
		in, out := &in.AutoScalingGroups, &out.AutoScalingGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.BlueGreenDeploymentConfiguration != nil {
		in, out := &in.BlueGreenDeploymentConfiguration, &out.BlueGreenDeploymentConfiguration
		*out = new(BlueGreenDeploymentConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.DeploymentConfigName != nil {
		in, out := &in.DeploymentConfigName, &out.DeploymentConfigName
		*out = new(string)
		**out = **in
	}
	if in.DeploymentGroupName != nil {
		in, out := &in.DeploymentGroupName, &out.DeploymentGroupName
		*out = new(string)
		**out = **in
	}
	if in.DeploymentStyle != nil {
		in, out := &in.DeploymentStyle, &out.DeploymentStyle
		*out = new(DeploymentStyle)
		(*in).DeepCopyInto(*out)
	}
	if in.EC2TagFilters != nil {
		in, out := &in.EC2TagFilters, &out.EC2TagFilters
		*out = make([]*EC2TagFilter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(EC2TagFilter)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.EC2TagSet != nil {
		in, out := &in.EC2TagSet, &out.EC2TagSet
		*out = new(EC2TagSet)
		(*in).DeepCopyInto(*out)
	}
	if in.EcsServices != nil {
		in, out := &in.EcsServices, &out.EcsServices
		*out = make([]*ECSService, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ECSService)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.LoadBalancerInfo != nil {
		in, out := &in.LoadBalancerInfo, &out.LoadBalancerInfo
		*out = new(LoadBalancerInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.OnPremisesInstanceTagFilters != nil {
		in, out := &in.OnPremisesInstanceTagFilters, &out.OnPremisesInstanceTagFilters
		*out = make([]*TagFilter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TagFilter)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.OnPremisesTagSet != nil {
		in, out := &in.OnPremisesTagSet, &out.OnPremisesTagSet
		*out = new(OnPremisesTagSet)
		(*in).DeepCopyInto(*out)
	}
	if in.OutdatedInstancesStrategy != nil {
		in, out := &in.OutdatedInstancesStrategy, &out.OutdatedInstancesStrategy
		*out = new(string)
		**out = **in
	}
	if in.ServiceRoleARN != nil {
		in, out := &in.ServiceRoleARN, &out.ServiceRoleARN
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.TriggerConfigurations != nil {
		in, out := &in.TriggerConfigurations, &out.TriggerConfigurations
		*out = make([]*TriggerConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TriggerConfig)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentGroupSpec.
func (in *DeploymentGroupSpec) DeepCopy() *DeploymentGroupSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentGroupStatus) DeepCopyInto(out *DeploymentGroupStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(v1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*v1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.DeploymentGroupID != nil {
		in, out := &in.DeploymentGroupID, &out.DeploymentGroupID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentGroupStatus.
func (in *DeploymentGroupStatus) DeepCopy() *DeploymentGroupStatus {
	if in == nil {
		return nil
	}
	out := new(DeploymentGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentInfo) DeepCopyInto(out *DeploymentInfo) {
	*out = *in
	if in.AdditionalDeploymentStatusInfo != nil {
		in, out := &in.AdditionalDeploymentStatusInfo, &out.AdditionalDeploymentStatusInfo
		*out = new(string)
		**out = **in
	}
	if in.ApplicationName != nil {
		in, out := &in.ApplicationName, &out.ApplicationName
		*out = new(string)
		**out = **in
	}
	if in.AutoRollbackConfiguration != nil {
		in, out := &in.AutoRollbackConfiguration, &out.AutoRollbackConfiguration
		*out = new(AutoRollbackConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.BlueGreenDeploymentConfiguration != nil {
		in, out := &in.BlueGreenDeploymentConfiguration, &out.BlueGreenDeploymentConfiguration
		*out = new(BlueGreenDeploymentConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.CompleteTime != nil {
		in, out := &in.CompleteTime, &out.CompleteTime
		*out = (*in).DeepCopy()
	}
	if in.ComputePlatform != nil {
		in, out := &in.ComputePlatform, &out.ComputePlatform
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = (*in).DeepCopy()
	}
	if in.Creator != nil {
		in, out := &in.Creator, &out.Creator
		*out = new(string)
		**out = **in
	}
	if in.DeploymentConfigName != nil {
		in, out := &in.DeploymentConfigName, &out.DeploymentConfigName
		*out = new(string)
		**out = **in
	}
	if in.DeploymentGroupName != nil {
		in, out := &in.DeploymentGroupName, &out.DeploymentGroupName
		*out = new(string)
		**out = **in
	}
	if in.DeploymentID != nil {
		in, out := &in.DeploymentID, &out.DeploymentID
		*out = new(string)
		**out = **in
	}
	if in.DeploymentOverview != nil {
		in, out := &in.DeploymentOverview, &out.DeploymentOverview
		*out = new(DeploymentOverview)
		(*in).DeepCopyInto(*out)
	}
	if in.DeploymentStatusMessages != nil {
		in, out := &in.DeploymentStatusMessages, &out.DeploymentStatusMessages
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DeploymentStyle != nil {
		in, out := &in.DeploymentStyle, &out.DeploymentStyle
		*out = new(DeploymentStyle)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ErrorInformation != nil {
		in, out := &in.ErrorInformation, &out.ErrorInformation
		*out = new(ErrorInformation)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalID != nil {
		in, out := &in.ExternalID, &out.ExternalID
		*out = new(string)
		**out = **in
	}
	if in.FileExistsBehavior != nil {
		in, out := &in.FileExistsBehavior, &out.FileExistsBehavior
		*out = new(string)
		**out = **in
	}
	if in.IgnoreApplicationStopFailures != nil {
		in, out := &in.IgnoreApplicationStopFailures, &out.IgnoreApplicationStopFailures
		*out = new(bool)
		**out = **in
	}
	if in.InstanceTerminationWaitTimeStarted != nil {
		in, out := &in.InstanceTerminationWaitTimeStarted, &out.InstanceTerminationWaitTimeStarted
		*out = new(bool)
		**out = **in
	}
	if in.LoadBalancerInfo != nil {
		in, out := &in.LoadBalancerInfo, &out.LoadBalancerInfo
		*out = new(LoadBalancerInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.PreviousRevision != nil {
		in, out := &in.PreviousRevision, &out.PreviousRevision
		*out = new(RevisionLocation)
		(*in).DeepCopyInto(*out)
	}
	if in.RelatedDeployments != nil {
		in, out := &in.RelatedDeployments, &out.RelatedDeployments
		*out = new(RelatedDeployments)
		(*in).DeepCopyInto(*out)
	}
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(RevisionLocation)
		(*in).DeepCopyInto(*out)
	}
	if in.RollbackInfo != nil {
		in, out := &in.RollbackInfo, &out.RollbackInfo
		*out = new(RollbackInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.TargetInstances != nil {
		in, out := &in.TargetInstances, &out.TargetInstances
		*out = new(TargetInstances)
		(*in).DeepCopyInto(*out)
	}
	if in.UpdateOutdatedInstancesOnly != nil {
		in, out := &in.UpdateOutdatedInstancesOnly, &out.UpdateOutdatedInstancesOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentInfo.
func (in *DeploymentInfo) DeepCopy() *DeploymentInfo {
	if in == nil {
		return nil
	}
	out := new(DeploymentInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentList) DeepCopyInto(out *DeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Deployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentList.
func (in *DeploymentList) DeepCopy() *DeploymentList {
	if in == nil {
		return nil
	}
	out := new(DeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentOverview) DeepCopyInto(out *DeploymentOverview) {
	*out = *in
	if in.Failed != nil {
		in, out := &in.Failed, &out.Failed
		*out = new(int64)
		**out = **in
	}
	if in.InProgress != nil {
		in, out := &in.InProgress, &out.InProgress
		*out = new(int64)
		**out = **in
	}
	if in.Pending != nil {
		in, out := &in.Pending, &out.Pending
		*out = new(int64)
		**out = **in
	}
	if in.Ready != nil {
		in, out := &in.Ready, &out.Ready
		*out = new(int64)
		**out = **in
	}
	if in.Skipped != nil {
		in, out := &in.Skipped, &out.Skipped
		*out = new(int64)
		**out = **in
	}
	if in.Succeeded != nil {
		in, out := &in.Succeeded, &out.Succeeded
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentOverview.
func (in *DeploymentOverview) DeepCopy() *DeploymentOverview {
	if in == nil {
		return nil
	}
	out := new(DeploymentOverview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentReadyOption) DeepCopyInto(out *DeploymentReadyOption) {
	*out = *in
	if in.ActionOnTimeout != nil {
		in, out := &in.ActionOnTimeout, &out.ActionOnTimeout
		*out = new(string)
		**out = **in
	}
	if in.WaitTimeInMinutes != nil {
		in, out := &in.WaitTimeInMinutes, &out.WaitTimeInMinutes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentReadyOption.
func (in *DeploymentReadyOption) DeepCopy() *DeploymentReadyOption {
	if in == nil {
		return nil
	}
	out := new(DeploymentReadyOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentSpec) DeepCopyInto(out *DeploymentSpec) {
	*out = *in
	if in.ApplicationName != nil {
		in, out := &in.ApplicationName, &out.ApplicationName
		*out = new(string)
		**out = **in
	}
	if in.AutoRollbackConfiguration != nil {
		in, out := &in.AutoRollbackConfiguration, &out.AutoRollbackConfiguration
		*out = new(AutoRollbackConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.DeploymentConfigName != nil {
		in, out := &in.DeploymentConfigName, &out.DeploymentConfigName
		*out = new(string)
		**out = **in
	}
	if in.DeploymentGroupName != nil {
		in, out := &in.DeploymentGroupName, &out.DeploymentGroupName
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FileExistsBehavior != nil {
		in, out := &in.FileExistsBehavior, &out.FileExistsBehavior
		*out = new(string)
		**out = **in
	}
	if in.IgnoreApplicationStopFailures != nil {
		in, out := &in.IgnoreApplicationStopFailures, &out.IgnoreApplicationStopFailures
		*out = new(bool)
		**out = **in
	}
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(RevisionLocation)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetInstances != nil {
		in, out := &in.TargetInstances, &out.TargetInstances
		*out = new(TargetInstances)
		(*in).DeepCopyInto(*out)
	}
	if in.UpdateOutdatedInstancesOnly != nil {
		in, out := &in.UpdateOutdatedInstancesOnly, &out.UpdateOutdatedInstancesOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentSpec.
func (in *DeploymentSpec) DeepCopy() *DeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentStatus) DeepCopyInto(out *DeploymentStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(v1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*v1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.DeploymentID != nil {
		in, out := &in.DeploymentID, &out.DeploymentID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentStatus.
func (in *DeploymentStatus) DeepCopy() *DeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(DeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentStyle) DeepCopyInto(out *DeploymentStyle) {
	*out = *in
	if in.DeploymentOption != nil {
		in, out := &in.DeploymentOption, &out.DeploymentOption
		*out = new(string)
		**out = **in
	}
	if in.DeploymentType != nil {
		in, out := &in.DeploymentType, &out.DeploymentType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentStyle.
func (in *DeploymentStyle) DeepCopy() *DeploymentStyle {
	if in == nil {
		return nil
	}
	out := new(DeploymentStyle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EC2TagFilter) DeepCopyInto(out *EC2TagFilter) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EC2TagFilter.
func (in *EC2TagFilter) DeepCopy() *EC2TagFilter {
	if in == nil {
		return nil
	}
	out := new(EC2TagFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EC2TagSet) DeepCopyInto(out *EC2TagSet) {
	*out = *in
	if in.EC2TagSetList != nil {
		in, out := &in.EC2TagSetList, &out.EC2TagSetList
		*out = make([][]*EC2TagFilter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]*EC2TagFilter, len(*in))
				for i := range *in {
					if (*in)[i] != nil {
						in, out := &(*in)[i], &(*out)[i]
						*out = new(EC2TagFilter)
						(*in).DeepCopyInto(*out)
					}
				}
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EC2TagSet.
func (in *EC2TagSet) DeepCopy() *EC2TagSet {
	if in == nil {
		return nil
	}
	out := new(EC2TagSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSService) DeepCopyInto(out *ECSService) {
	*out = *in
	if in.ClusterName != nil {
		in, out := &in.ClusterName, &out.ClusterName
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSService.
func (in *ECSService) DeepCopy() *ECSService {
	if in == nil {
		return nil
	}
	out := new(ECSService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSTarget) DeepCopyInto(out *ECSTarget) {
	*out = *in
	if in.DeploymentID != nil {
		in, out := &in.DeploymentID, &out.DeploymentID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSTarget.
func (in *ECSTarget) DeepCopy() *ECSTarget {
	if in == nil {
		return nil
	}
	out := new(ECSTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECSTaskSet) DeepCopyInto(out *ECSTaskSet) {
	*out = *in
	if in.TargetGroup != nil {
		in, out := &in.TargetGroup, &out.TargetGroup
		*out = new(TargetGroupInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECSTaskSet.
func (in *ECSTaskSet) DeepCopy() *ECSTaskSet {
	if in == nil {
		return nil
	}
	out := new(ECSTaskSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ELBInfo) DeepCopyInto(out *ELBInfo) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ELBInfo.
func (in *ELBInfo) DeepCopy() *ELBInfo {
	if in == nil {
		return nil
	}
	out := new(ELBInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorInformation) DeepCopyInto(out *ErrorInformation) {
	*out = *in
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorInformation.
func (in *ErrorInformation) DeepCopy() *ErrorInformation {
	if in == nil {
		return nil
	}
	out := new(ErrorInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericRevisionInfo) DeepCopyInto(out *GenericRevisionInfo) {
	*out = *in
	if in.DeploymentGroups != nil {
		in, out := &in.DeploymentGroups, &out.DeploymentGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FirstUsedTime != nil {
		in, out := &in.FirstUsedTime, &out.FirstUsedTime
		*out = (*in).DeepCopy()
	}
	if in.LastUsedTime != nil {
		in, out := &in.LastUsedTime, &out.LastUsedTime
		*out = (*in).DeepCopy()
	}
	if in.RegisterTime != nil {
		in, out := &in.RegisterTime, &out.RegisterTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericRevisionInfo.
func (in *GenericRevisionInfo) DeepCopy() *GenericRevisionInfo {
	if in == nil {
		return nil
	}
	out := new(GenericRevisionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubLocation) DeepCopyInto(out *GitHubLocation) {
	*out = *in
	if in.CommitID != nil {
		in, out := &in.CommitID, &out.CommitID
		*out = new(string)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubLocation.
func (in *GitHubLocation) DeepCopy() *GitHubLocation {
	if in == nil {
		return nil
	}
	out := new(GitHubLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreenFleetProvisioningOption) DeepCopyInto(out *GreenFleetProvisioningOption) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreenFleetProvisioningOption.
func (in *GreenFleetProvisioningOption) DeepCopy() *GreenFleetProvisioningOption {
	if in == nil {
		return nil
	}
	out := new(GreenFleetProvisioningOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceInfo) DeepCopyInto(out *InstanceInfo) {
	*out = *in
	if in.DeregisterTime != nil {
		in, out := &in.DeregisterTime, &out.DeregisterTime
		*out = (*in).DeepCopy()
	}
	if in.RegisterTime != nil {
		in, out := &in.RegisterTime, &out.RegisterTime
		*out = (*in).DeepCopy()
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceInfo.
func (in *InstanceInfo) DeepCopy() *InstanceInfo {
	if in == nil {
		return nil
	}
	out := new(InstanceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceSummary) DeepCopyInto(out *InstanceSummary) {
	*out = *in
	if in.DeploymentID != nil {
		in, out := &in.DeploymentID, &out.DeploymentID
		*out = new(string)
		**out = **in
	}
	if in.LastUpdatedAt != nil {
		in, out := &in.LastUpdatedAt, &out.LastUpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceSummary.
func (in *InstanceSummary) DeepCopy() *InstanceSummary {
	if in == nil {
		return nil
	}
	out := new(InstanceSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceTarget) DeepCopyInto(out *InstanceTarget) {
	*out = *in
	if in.DeploymentID != nil {
		in, out := &in.DeploymentID, &out.DeploymentID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceTarget.
func (in *InstanceTarget) DeepCopy() *InstanceTarget {
	if in == nil {
		return nil
	}
	out := new(InstanceTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LambdaTarget) DeepCopyInto(out *LambdaTarget) {
	*out = *in
	if in.DeploymentID != nil {
		in, out := &in.DeploymentID, &out.DeploymentID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LambdaTarget.
func (in *LambdaTarget) DeepCopy() *LambdaTarget {
	if in == nil {
		return nil
	}
	out := new(LambdaTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastDeploymentInfo) DeepCopyInto(out *LastDeploymentInfo) {
	*out = *in
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = (*in).DeepCopy()
	}
	if in.DeploymentID != nil {
		in, out := &in.DeploymentID, &out.DeploymentID
		*out = new(string)
		**out = **in
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastDeploymentInfo.
func (in *LastDeploymentInfo) DeepCopy() *LastDeploymentInfo {
	if in == nil {
		return nil
	}
	out := new(LastDeploymentInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleEvent) DeepCopyInto(out *LifecycleEvent) {
	*out = *in
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleEvent.
func (in *LifecycleEvent) DeepCopy() *LifecycleEvent {
	if in == nil {
		return nil
	}
	out := new(LifecycleEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerInfo) DeepCopyInto(out *LoadBalancerInfo) {
	*out = *in
	if in.ElbInfoList != nil {
		in, out := &in.ElbInfoList, &out.ElbInfoList
		*out = make([]*ELBInfo, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ELBInfo)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.TargetGroupInfoList != nil {
		in, out := &in.TargetGroupInfoList, &out.TargetGroupInfoList
		*out = make([]*TargetGroupInfo, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TargetGroupInfo)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.TargetGroupPairInfoList != nil {
		in, out := &in.TargetGroupPairInfoList, &out.TargetGroupPairInfoList
		*out = make([]*TargetGroupPairInfo, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TargetGroupPairInfo)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerInfo.
func (in *LoadBalancerInfo) DeepCopy() *LoadBalancerInfo {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinimumHealthyHosts) DeepCopyInto(out *MinimumHealthyHosts) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinimumHealthyHosts.
func (in *MinimumHealthyHosts) DeepCopy() *MinimumHealthyHosts {
	if in == nil {
		return nil
	}
	out := new(MinimumHealthyHosts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnPremisesTagSet) DeepCopyInto(out *OnPremisesTagSet) {
	*out = *in
	if in.OnPremisesTagSetList != nil {
		in, out := &in.OnPremisesTagSetList, &out.OnPremisesTagSetList
		*out = make([][]*TagFilter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]*TagFilter, len(*in))
				for i := range *in {
					if (*in)[i] != nil {
						in, out := &(*in)[i], &(*out)[i]
						*out = new(TagFilter)
						(*in).DeepCopyInto(*out)
					}
				}
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnPremisesTagSet.
func (in *OnPremisesTagSet) DeepCopy() *OnPremisesTagSet {
	if in == nil {
		return nil
	}
	out := new(OnPremisesTagSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RawString) DeepCopyInto(out *RawString) {
	*out = *in
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(string)
		**out = **in
	}
	if in.SHA256 != nil {
		in, out := &in.SHA256, &out.SHA256
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawString.
func (in *RawString) DeepCopy() *RawString {
	if in == nil {
		return nil
	}
	out := new(RawString)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelatedDeployments) DeepCopyInto(out *RelatedDeployments) {
	*out = *in
	if in.AutoUpdateOutdatedInstancesDeploymentIDs != nil {
		in, out := &in.AutoUpdateOutdatedInstancesDeploymentIDs, &out.AutoUpdateOutdatedInstancesDeploymentIDs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AutoUpdateOutdatedInstancesRootDeploymentID != nil {
		in, out := &in.AutoUpdateOutdatedInstancesRootDeploymentID, &out.AutoUpdateOutdatedInstancesRootDeploymentID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelatedDeployments.
func (in *RelatedDeployments) DeepCopy() *RelatedDeployments {
	if in == nil {
		return nil
	}
	out := new(RelatedDeployments)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevisionInfo) DeepCopyInto(out *RevisionInfo) {
	*out = *in
	if in.RevisionLocation != nil {
		in, out := &in.RevisionLocation, &out.RevisionLocation
		*out = new(RevisionLocation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevisionInfo.
func (in *RevisionInfo) DeepCopy() *RevisionInfo {
	if in == nil {
		return nil
	}
	out := new(RevisionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevisionLocation) DeepCopyInto(out *RevisionLocation) {
	*out = *in
	if in.AppSpecContent != nil {
		in, out := &in.AppSpecContent, &out.AppSpecContent
		*out = new(AppSpecContent)
		(*in).DeepCopyInto(*out)
	}
	if in.GitHubLocation != nil {
		in, out := &in.GitHubLocation, &out.GitHubLocation
		*out = new(GitHubLocation)
		(*in).DeepCopyInto(*out)
	}
	if in.RevisionType != nil {
		in, out := &in.RevisionType, &out.RevisionType
		*out = new(string)
		**out = **in
	}
	if in.S3Location != nil {
		in, out := &in.S3Location, &out.S3Location
		*out = new(S3Location)
		(*in).DeepCopyInto(*out)
	}
	if in.String != nil {
		in, out := &in.String, &out.String
		*out = new(RawString)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevisionLocation.
func (in *RevisionLocation) DeepCopy() *RevisionLocation {
	if in == nil {
		return nil
	}
	out := new(RevisionLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollbackInfo) DeepCopyInto(out *RollbackInfo) {
	*out = *in
	if in.RollbackDeploymentID != nil {
		in, out := &in.RollbackDeploymentID, &out.RollbackDeploymentID
		*out = new(string)
		**out = **in
	}
	if in.RollbackMessage != nil {
		in, out := &in.RollbackMessage, &out.RollbackMessage
		*out = new(string)
		**out = **in
	}
	if in.RollbackTriggeringDeploymentID != nil {
		in, out := &in.RollbackTriggeringDeploymentID, &out.RollbackTriggeringDeploymentID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollbackInfo.
func (in *RollbackInfo) DeepCopy() *RollbackInfo {
	if in == nil {
		return nil
	}
	out := new(RollbackInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Location) DeepCopyInto(out *S3Location) {
	*out = *in
	if in.Bucket != nil {
		in, out := &in.Bucket, &out.Bucket
		*out = new(string)
		**out = **in
	}
	if in.BundleType != nil {
		in, out := &in.BundleType, &out.BundleType
		*out = new(string)
		**out = **in
	}
	if in.ETag != nil {
		in, out := &in.ETag, &out.ETag
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Location.
func (in *S3Location) DeepCopy() *S3Location {
	if in == nil {
		return nil
	}
	out := new(S3Location)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagFilter) DeepCopyInto(out *TagFilter) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagFilter.
func (in *TagFilter) DeepCopy() *TagFilter {
	if in == nil {
		return nil
	}
	out := new(TagFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetGroupInfo) DeepCopyInto(out *TargetGroupInfo) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetGroupInfo.
func (in *TargetGroupInfo) DeepCopy() *TargetGroupInfo {
	if in == nil {
		return nil
	}
	out := new(TargetGroupInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetGroupPairInfo) DeepCopyInto(out *TargetGroupPairInfo) {
	*out = *in
	if in.ProdTrafficRoute != nil {
		in, out := &in.ProdTrafficRoute, &out.ProdTrafficRoute
		*out = new(TrafficRoute)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetGroups != nil {
		in, out := &in.TargetGroups, &out.TargetGroups
		*out = make([]*TargetGroupInfo, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(TargetGroupInfo)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.TestTrafficRoute != nil {
		in, out := &in.TestTrafficRoute, &out.TestTrafficRoute
		*out = new(TrafficRoute)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetGroupPairInfo.
func (in *TargetGroupPairInfo) DeepCopy() *TargetGroupPairInfo {
	if in == nil {
		return nil
	}
	out := new(TargetGroupPairInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetInstances) DeepCopyInto(out *TargetInstances) {
	*out = *in
	if in.AutoScalingGroups != nil {
		in, out := &in.AutoScalingGroups, &out.AutoScalingGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EC2TagSet != nil {
		in, out := &in.EC2TagSet, &out.EC2TagSet
		*out = new(EC2TagSet)
		(*in).DeepCopyInto(*out)
	}
	if in.TagFilters != nil {
		in, out := &in.TagFilters, &out.TagFilters
		*out = make([]*EC2TagFilter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(EC2TagFilter)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetInstances.
func (in *TargetInstances) DeepCopy() *TargetInstances {
	if in == nil {
		return nil
	}
	out := new(TargetInstances)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeBasedCanary) DeepCopyInto(out *TimeBasedCanary) {
	*out = *in
	if in.CanaryInterval != nil {
		in, out := &in.CanaryInterval, &out.CanaryInterval
		*out = new(int64)
		**out = **in
	}
	if in.CanaryPercentage != nil {
		in, out := &in.CanaryPercentage, &out.CanaryPercentage
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeBasedCanary.
func (in *TimeBasedCanary) DeepCopy() *TimeBasedCanary {
	if in == nil {
		return nil
	}
	out := new(TimeBasedCanary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeBasedLinear) DeepCopyInto(out *TimeBasedLinear) {
	*out = *in
	if in.LinearInterval != nil {
		in, out := &in.LinearInterval, &out.LinearInterval
		*out = new(int64)
		**out = **in
	}
	if in.LinearPercentage != nil {
		in, out := &in.LinearPercentage, &out.LinearPercentage
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeBasedLinear.
func (in *TimeBasedLinear) DeepCopy() *TimeBasedLinear {
	if in == nil {
		return nil
	}
	out := new(TimeBasedLinear)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeRange) DeepCopyInto(out *TimeRange) {
	*out = *in
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = (*in).DeepCopy()
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeRange.
func (in *TimeRange) DeepCopy() *TimeRange {
	if in == nil {
		return nil
	}
	out := new(TimeRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficRoute) DeepCopyInto(out *TrafficRoute) {
	*out = *in
	if in.ListenerARNs != nil {
		in, out := &in.ListenerARNs, &out.ListenerARNs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficRoute.
func (in *TrafficRoute) DeepCopy() *TrafficRoute {
	if in == nil {
		return nil
	}
	out := new(TrafficRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficRoutingConfig) DeepCopyInto(out *TrafficRoutingConfig) {
	*out = *in
	if in.TimeBasedCanary != nil {
		in, out := &in.TimeBasedCanary, &out.TimeBasedCanary
		*out = new(TimeBasedCanary)
		(*in).DeepCopyInto(*out)
	}
	if in.TimeBasedLinear != nil {
		in, out := &in.TimeBasedLinear, &out.TimeBasedLinear
		*out = new(TimeBasedLinear)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficRoutingConfig.
func (in *TrafficRoutingConfig) DeepCopy() *TrafficRoutingConfig {
	if in == nil {
		return nil
	}
	out := new(TrafficRoutingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerConfig) DeepCopyInto(out *TriggerConfig) {
	*out = *in
	if in.TriggerEvents != nil {
		in, out := &in.TriggerEvents, &out.TriggerEvents
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TriggerName != nil {
		in, out := &in.TriggerName, &out.TriggerName
		*out = new(string)
		**out = **in
	}
	if in.TriggerTargetARN != nil {
		in, out := &in.TriggerTargetARN, &out.TriggerTargetARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerConfig.
func (in *TriggerConfig) DeepCopy() *TriggerConfig {
	if in == nil {
		return nil
	}
	out := new(TriggerConfig)
	in.DeepCopyInto(out)
	return out
}
