// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type ApplicationRevisionSortBy string

const (
	ApplicationRevisionSortBy_registerTime ApplicationRevisionSortBy = "registerTime"
	ApplicationRevisionSortBy_firstUsedTime ApplicationRevisionSortBy = "firstUsedTime"
	ApplicationRevisionSortBy_lastUsedTime ApplicationRevisionSortBy = "lastUsedTime"
)

type AutoRollbackEvent string

const (
	AutoRollbackEvent_DEPLOYMENT_FAILURE AutoRollbackEvent = "DEPLOYMENT_FAILURE"
	AutoRollbackEvent_DEPLOYMENT_STOP_ON_ALARM AutoRollbackEvent = "DEPLOYMENT_STOP_ON_ALARM"
	AutoRollbackEvent_DEPLOYMENT_STOP_ON_REQUEST AutoRollbackEvent = "DEPLOYMENT_STOP_ON_REQUEST"
)

type BundleType string

const (
	BundleType_tar BundleType = "tar"
	BundleType_tgz BundleType = "tgz"
	BundleType_zip BundleType = "zip"
	BundleType_YAML BundleType = "YAML"
	BundleType_JSON BundleType = "JSON"
)

type ComputePlatform string

const (
	ComputePlatform_Server ComputePlatform = "Server"
	ComputePlatform_Lambda ComputePlatform = "Lambda"
	ComputePlatform_ECS ComputePlatform = "ECS"
)

type DeploymentCreator string

const (
	DeploymentCreator_user DeploymentCreator = "user"
	DeploymentCreator_autoscaling DeploymentCreator = "autoscaling"
	DeploymentCreator_codeDeployRollback DeploymentCreator = "codeDeployRollback"
	DeploymentCreator_CodeDeploy DeploymentCreator = "CodeDeploy"
	DeploymentCreator_CodeDeployAutoUpdate DeploymentCreator = "CodeDeployAutoUpdate"
	DeploymentCreator_CloudFormation DeploymentCreator = "CloudFormation"
	DeploymentCreator_CloudFormationRollback DeploymentCreator = "CloudFormationRollback"
)

type DeploymentOption string

const (
	DeploymentOption_WITH_TRAFFIC_CONTROL DeploymentOption = "WITH_TRAFFIC_CONTROL"
	DeploymentOption_WITHOUT_TRAFFIC_CONTROL DeploymentOption = "WITHOUT_TRAFFIC_CONTROL"
)

type DeploymentReadyAction string

const (
	DeploymentReadyAction_CONTINUE_DEPLOYMENT DeploymentReadyAction = "CONTINUE_DEPLOYMENT"
	DeploymentReadyAction_STOP_DEPLOYMENT DeploymentReadyAction = "STOP_DEPLOYMENT"
)

type DeploymentStatus_SDK string

const (
	DeploymentStatus_SDK_Created DeploymentStatus_SDK = "Created"
	DeploymentStatus_SDK_Queued DeploymentStatus_SDK = "Queued"
	DeploymentStatus_SDK_InProgress DeploymentStatus_SDK = "InProgress"
	DeploymentStatus_SDK_Baking DeploymentStatus_SDK = "Baking"
	DeploymentStatus_SDK_Succeeded DeploymentStatus_SDK = "Succeeded"
	DeploymentStatus_SDK_Failed DeploymentStatus_SDK = "Failed"
	DeploymentStatus_SDK_Stopped DeploymentStatus_SDK = "Stopped"
	DeploymentStatus_SDK_Ready DeploymentStatus_SDK = "Ready"
)

type DeploymentTargetType string

const (
	DeploymentTargetType_InstanceTarget DeploymentTargetType = "InstanceTarget"
	DeploymentTargetType_LambdaTarget DeploymentTargetType = "LambdaTarget"
	DeploymentTargetType_ECSTarget DeploymentTargetType = "ECSTarget"
	DeploymentTargetType_CloudFormationTarget DeploymentTargetType = "CloudFormationTarget"
)

type DeploymentType string

const (
	DeploymentType_IN_PLACE DeploymentType = "IN_PLACE"
	DeploymentType_BLUE_GREEN DeploymentType = "BLUE_GREEN"
)

type DeploymentWaitType string

const (
	DeploymentWaitType_READY_WAIT DeploymentWaitType = "READY_WAIT"
	DeploymentWaitType_TERMINATION_WAIT DeploymentWaitType = "TERMINATION_WAIT"
)

type EC2TagFilterType string

const (
	EC2TagFilterType_KEY_ONLY EC2TagFilterType = "KEY_ONLY"
	EC2TagFilterType_VALUE_ONLY EC2TagFilterType = "VALUE_ONLY"
	EC2TagFilterType_KEY_AND_VALUE EC2TagFilterType = "KEY_AND_VALUE"
)

type ErrorCode string

const (
	ErrorCode_AGENT_ISSUE ErrorCode = "AGENT_ISSUE"
	ErrorCode_ALARM_ACTIVE ErrorCode = "ALARM_ACTIVE"
	ErrorCode_APPLICATION_MISSING ErrorCode = "APPLICATION_MISSING"
	ErrorCode_AUTOSCALING_VALIDATION_ERROR ErrorCode = "AUTOSCALING_VALIDATION_ERROR"
	ErrorCode_AUTO_SCALING_CONFIGURATION ErrorCode = "AUTO_SCALING_CONFIGURATION"
	ErrorCode_AUTO_SCALING_IAM_ROLE_PERMISSIONS ErrorCode = "AUTO_SCALING_IAM_ROLE_PERMISSIONS"
	ErrorCode_CODEDEPLOY_RESOURCE_CANNOT_BE_FOUND ErrorCode = "CODEDEPLOY_RESOURCE_CANNOT_BE_FOUND"
	ErrorCode_CUSTOMER_APPLICATION_UNHEALTHY ErrorCode = "CUSTOMER_APPLICATION_UNHEALTHY"
	ErrorCode_DEPLOYMENT_GROUP_MISSING ErrorCode = "DEPLOYMENT_GROUP_MISSING"
	ErrorCode_ECS_UPDATE_ERROR ErrorCode = "ECS_UPDATE_ERROR"
	ErrorCode_ELASTIC_LOAD_BALANCING_INVALID ErrorCode = "ELASTIC_LOAD_BALANCING_INVALID"
	ErrorCode_ELB_INVALID_INSTANCE ErrorCode = "ELB_INVALID_INSTANCE"
	ErrorCode_HEALTH_CONSTRAINTS ErrorCode = "HEALTH_CONSTRAINTS"
	ErrorCode_HEALTH_CONSTRAINTS_INVALID ErrorCode = "HEALTH_CONSTRAINTS_INVALID"
	ErrorCode_HOOK_EXECUTION_FAILURE ErrorCode = "HOOK_EXECUTION_FAILURE"
	ErrorCode_IAM_ROLE_MISSING ErrorCode = "IAM_ROLE_MISSING"
	ErrorCode_IAM_ROLE_PERMISSIONS ErrorCode = "IAM_ROLE_PERMISSIONS"
	ErrorCode_INTERNAL_ERROR ErrorCode = "INTERNAL_ERROR"
	ErrorCode_INVALID_ECS_SERVICE ErrorCode = "INVALID_ECS_SERVICE"
	ErrorCode_INVALID_LAMBDA_CONFIGURATION ErrorCode = "INVALID_LAMBDA_CONFIGURATION"
	ErrorCode_INVALID_LAMBDA_FUNCTION ErrorCode = "INVALID_LAMBDA_FUNCTION"
	ErrorCode_INVALID_REVISION ErrorCode = "INVALID_REVISION"
	ErrorCode_MANUAL_STOP ErrorCode = "MANUAL_STOP"
	ErrorCode_MISSING_BLUE_GREEN_DEPLOYMENT_CONFIGURATION ErrorCode = "MISSING_BLUE_GREEN_DEPLOYMENT_CONFIGURATION"
	ErrorCode_MISSING_ELB_INFORMATION ErrorCode = "MISSING_ELB_INFORMATION"
	ErrorCode_MISSING_GITHUB_TOKEN ErrorCode = "MISSING_GITHUB_TOKEN"
	ErrorCode_NO_EC2_SUBSCRIPTION ErrorCode = "NO_EC2_SUBSCRIPTION"
	ErrorCode_NO_INSTANCES ErrorCode = "NO_INSTANCES"
	ErrorCode_OVER_MAX_INSTANCES ErrorCode = "OVER_MAX_INSTANCES"
	ErrorCode_RESOURCE_LIMIT_EXCEEDED ErrorCode = "RESOURCE_LIMIT_EXCEEDED"
	ErrorCode_REVISION_MISSING ErrorCode = "REVISION_MISSING"
	ErrorCode_THROTTLED ErrorCode = "THROTTLED"
	ErrorCode_TIMEOUT ErrorCode = "TIMEOUT"
	ErrorCode_CLOUDFORMATION_STACK_FAILURE ErrorCode = "CLOUDFORMATION_STACK_FAILURE"
)

type FileExistsBehavior string

const (
	FileExistsBehavior_DISALLOW FileExistsBehavior = "DISALLOW"
	FileExistsBehavior_OVERWRITE FileExistsBehavior = "OVERWRITE"
	FileExistsBehavior_RETAIN FileExistsBehavior = "RETAIN"
)

type GreenFleetProvisioningAction string

const (
	GreenFleetProvisioningAction_DISCOVER_EXISTING GreenFleetProvisioningAction = "DISCOVER_EXISTING"
	GreenFleetProvisioningAction_COPY_AUTO_SCALING_GROUP GreenFleetProvisioningAction = "COPY_AUTO_SCALING_GROUP"
)

type InstanceAction string

const (
	InstanceAction_TERMINATE InstanceAction = "TERMINATE"
	InstanceAction_KEEP_ALIVE InstanceAction = "KEEP_ALIVE"
)

type InstanceStatus string

const (
	InstanceStatus_Pending InstanceStatus = "Pending"
	InstanceStatus_InProgress InstanceStatus = "InProgress"
	InstanceStatus_Succeeded InstanceStatus = "Succeeded"
	InstanceStatus_Failed InstanceStatus = "Failed"
	InstanceStatus_Skipped InstanceStatus = "Skipped"
	InstanceStatus_Unknown InstanceStatus = "Unknown"
	InstanceStatus_Ready InstanceStatus = "Ready"
)

type InstanceType string

const (
	InstanceType_Blue InstanceType = "Blue"
	InstanceType_Green InstanceType = "Green"
)

type LifecycleErrorCode string

const (
	LifecycleErrorCode_Success LifecycleErrorCode = "Success"
	LifecycleErrorCode_ScriptMissing LifecycleErrorCode = "ScriptMissing"
	LifecycleErrorCode_ScriptNotExecutable LifecycleErrorCode = "ScriptNotExecutable"
	LifecycleErrorCode_ScriptTimedOut LifecycleErrorCode = "ScriptTimedOut"
	LifecycleErrorCode_ScriptFailed LifecycleErrorCode = "ScriptFailed"
	LifecycleErrorCode_UnknownError LifecycleErrorCode = "UnknownError"
)

type LifecycleEventStatus string

const (
	LifecycleEventStatus_Pending LifecycleEventStatus = "Pending"
	LifecycleEventStatus_InProgress LifecycleEventStatus = "InProgress"
	LifecycleEventStatus_Succeeded LifecycleEventStatus = "Succeeded"
	LifecycleEventStatus_Failed LifecycleEventStatus = "Failed"
	LifecycleEventStatus_Skipped LifecycleEventStatus = "Skipped"
	LifecycleEventStatus_Unknown LifecycleEventStatus = "Unknown"
)

type ListStateFilterAction string

const (
	ListStateFilterAction_include ListStateFilterAction = "include"
	ListStateFilterAction_exclude ListStateFilterAction = "exclude"
	ListStateFilterAction_ignore ListStateFilterAction = "ignore"
)

type MinimumHealthyHostsType string

const (
	MinimumHealthyHostsType_HOST_COUNT MinimumHealthyHostsType = "HOST_COUNT"
	MinimumHealthyHostsType_FLEET_PERCENT MinimumHealthyHostsType = "FLEET_PERCENT"
)

type OutdatedInstancesStrategy string

const (
	OutdatedInstancesStrategy_UPDATE OutdatedInstancesStrategy = "UPDATE"
	OutdatedInstancesStrategy_IGNORE OutdatedInstancesStrategy = "IGNORE"
)

type RegistrationStatus string

const (
	RegistrationStatus_Registered RegistrationStatus = "Registered"
	RegistrationStatus_Deregistered RegistrationStatus = "Deregistered"
)

type RevisionLocationType string

const (
	RevisionLocationType_S3 RevisionLocationType = "S3"
	RevisionLocationType_GitHub RevisionLocationType = "GitHub"
	RevisionLocationType_String RevisionLocationType = "String"
	RevisionLocationType_AppSpecContent RevisionLocationType = "AppSpecContent"
)

type SortOrder string

const (
	SortOrder_ascending SortOrder = "ascending"
	SortOrder_descending SortOrder = "descending"
)

type StopStatus string

const (
	StopStatus_Pending StopStatus = "Pending"
	StopStatus_Succeeded StopStatus = "Succeeded"
)

type TagFilterType string

const (
	TagFilterType_KEY_ONLY TagFilterType = "KEY_ONLY"
	TagFilterType_VALUE_ONLY TagFilterType = "VALUE_ONLY"
	TagFilterType_KEY_AND_VALUE TagFilterType = "KEY_AND_VALUE"
)

type TargetFilterName string

const (
	TargetFilterName_TargetStatus TargetFilterName = "TargetStatus"
	TargetFilterName_ServerInstanceLabel TargetFilterName = "ServerInstanceLabel"
)

type TargetLabel string

const (
	TargetLabel_Blue TargetLabel = "Blue"
	TargetLabel_Green TargetLabel = "Green"
)

type TargetStatus string

const (
	TargetStatus_Pending TargetStatus = "Pending"
	TargetStatus_InProgress TargetStatus = "InProgress"
	TargetStatus_Succeeded TargetStatus = "Succeeded"
	TargetStatus_Failed TargetStatus = "Failed"
	TargetStatus_Skipped TargetStatus = "Skipped"
	TargetStatus_Unknown TargetStatus = "Unknown"
	TargetStatus_Ready TargetStatus = "Ready"
)

type TrafficRoutingType string

const (
	TrafficRoutingType_TimeBasedCanary TrafficRoutingType = "TimeBasedCanary"
	TrafficRoutingType_TimeBasedLinear TrafficRoutingType = "TimeBasedLinear"
	TrafficRoutingType_AllAtOnce TrafficRoutingType = "AllAtOnce"
)

type TriggerEventType string

const (
	TriggerEventType_DeploymentStart TriggerEventType = "DeploymentStart"
	TriggerEventType_DeploymentSuccess TriggerEventType = "DeploymentSuccess"
	TriggerEventType_DeploymentFailure TriggerEventType = "DeploymentFailure"
	TriggerEventType_DeploymentStop TriggerEventType = "DeploymentStop"
	TriggerEventType_DeploymentRollback TriggerEventType = "DeploymentRollback"
	TriggerEventType_DeploymentReady TriggerEventType = "DeploymentReady"
	TriggerEventType_InstanceStart TriggerEventType = "InstanceStart"
	TriggerEventType_InstanceSuccess TriggerEventType = "InstanceSuccess"
	TriggerEventType_InstanceFailure TriggerEventType = "InstanceFailure"
	TriggerEventType_InstanceReady TriggerEventType = "InstanceReady"
)